User permissions
alphagov/co-eu-transition-dashboard pull request #225
Opened 2020-08-14 14:36 UTC by AhdabNasir

2020-08-18 13:01 UTC, gds-gharper commented on models/role.js
> +    type: ENUM('uploader', 'viewer', 'admin', 'management', 'guest')
This should just be STRING, not an ENUM, we'll be wanting to add to the table and shouldn't have to change this section of the code for that (obviously we'll have to update the code to check for the roles).

2020-08-18 13:03 UTC, gds-gharper commented on test/unit/models/role.test.js
> +        type: ENUM('uploader', 'viewer', 'admin', 'management', 'guest')
Again, this should be a string

2020-08-24 11:45 UTC, AhdabNasir commented
> Looks pretty good some things below. Mainly we should only be checking for one role, unless there are specific pages which require multiple roles (admin AND viewer for instance). If users need the viewer role then it should be added.
> 
> This allows for a user to be an admin but not a viewer for instance (which is something that might happen).

2020-08-25 08:43 UTC, gds-gharper requested changes

2020-08-25 08:43 UTC, gds-gharper commented on pages/all-data/AllData.js
> +      ...authentication.protect(['admin', 'uploaders', 'viewer', 'management'])
Surely we should only be checking for viewer here?

2020-08-25 08:43 UTC, gds-gharper commented on pages/authentication/password-reset/PasswordReset.js
> +      ...authentication.protect(['uploader', 'viewer', 'admin', 'management', 'guest']),
Here we don't need to check for a role, we simply need to check the user is logged in.  Everyone should be able to access this page (everyone who has an account).

2020-08-25 08:43 UTC, gds-gharper commented on pages/data-entry/bulk-upload/BulkUpload.js
> +      ...authentication.protect(['uploader', 'admin']),
Only check for uploader here admins will also get the uploader role if they need it.

2020-08-25 08:43 UTC, gds-gharper commented on pages/data-entry/import/Import.js
> +      ...authentication.protect(['uploader', 'admin']),
Same here, only check for uploader.

2020-08-25 08:43 UTC, gds-gharper commented on pages/data-entry/project-milestone-template/ProjectMilestoneTemplate.js
> +      ...authentication.protect(['uploader', 'admin'])
Don't check for admin.

2020-08-25 08:43 UTC, gds-gharper commented on pages/data-entry/submission-success/SubmissionSuccess.js
> +      ...authentication.protect(['uploader', 'admin'])
Don't check for admin

2020-08-25 08:43 UTC, gds-gharper commented on pages/edit-milestone/EditMilestone.js
> +      ...authentication.protect(['uploader', 'admin']),
Don't check for admin

2020-08-25 08:43 UTC, gds-gharper commented on pages/edit-project/EditProject.js
> +      ...authentication.protect(['uploader', 'admin']),
Don't check for admin

2020-08-25 08:43 UTC, gds-gharper commented on pages/milestone-details/MilestoneDetails.html
> +      {% if req.user.roles | includes(['admin', 'uploader']) %}
Don't check for admin

2020-08-25 08:43 UTC, gds-gharper commented on pages/milestone-details/MilestoneDetails.js
> +      ...authentication.protect(['uploader', 'admin', 'viewer', 'management'])
Should only check for viewer here?

2020-08-25 08:43 UTC, gds-gharper commented on pages/missed-milestones/MissedMilestones.js
> +      ...authentication.protect(['uploader', 'admin', 'viewer', 'management'])
viewer only

2020-08-25 08:43 UTC, gds-gharper commented on pages/project-details/ProjectDetails.html
> +{% if req.user.roles | includes(['admin', 'uploader']) %}
Just check for uploader

2020-08-25 08:43 UTC, gds-gharper commented on pages/project-details/ProjectDetails.html
> +    {% if req.user.roles | includes(['admin', 'uploader']) %}
Just check for uploader

2020-08-25 08:43 UTC, gds-gharper commented on pages/project-details/ProjectDetails.html
> +    {% if req.user.roles | includes(['admin', 'uploader']) %}
Just check for uploader

2020-08-25 08:43 UTC, gds-gharper commented on pages/project-details/ProjectDetails.js
> +      ...authentication.protect(['uploader', 'admin', 'viewer', 'management'])
Only check for viewer?

2020-08-25 08:43 UTC, gds-gharper commented on pages/reporting-overview/ReportingOverview.js
> +      ...authentication.protect(['admin', 'viewer', 'uploader'])
Only check for viewer

2020-08-25 08:43 UTC, gds-gharper commented on pages/upcoming-milestones/UpcomingMilestones.js
> +      ...authentication.protect(['uploader', 'admin', 'viewer', 'management'])
Viewer only

2020-08-25 08:43 UTC, gds-gharper commented on services/authentication.js
> +      model: Role
Surely it should be including UserRole rather than Role?  The role table doesn't join directly onto the user table

2020-08-25 12:39 UTC, AhdabNasir commented on services/authentication.js
> +      model: Role
I think Role is correct and it works fine. I tried UserRole and it didn't.

2020-08-25 12:40 UTC, AhdabNasir commented on pages/authentication/password-reset/PasswordReset.js
> +      ...authentication.protect(['uploader', 'viewer', 'admin', 'management', 'guest']),
This is the way the authentication journey is built. I just added onto this to include the new roles.

2020-08-25 13:12 UTC, gds-gharper requested changes

2020-08-25 13:12 UTC, gds-gharper commented on core/pages/page.js
> +    return [...protect(['uploader', 'viewer', 'admin', 'management', 'management_overview'])];
What does this default do, it essentially sets a default that any page can be viewed by a user with any role.  I'd be tempted to set a more sensible default (or force the function to be overridden).  Perhaps viewer might be a sensible default?

2020-08-25 13:12 UTC, gds-gharper commented on pages/authentication/password-reset/PasswordReset.js
> +      ...authentication.protect(['uploader', 'viewer', 'admin', 'management', 'management_overview']),
This should simply check for a user being logged in, rather than looking for a specific role.

2020-08-25 13:12 UTC, gds-gharper commented on services/authentication.js
> +      model: Role
Ah I see, the relationship marks it with a through.

2020-08-26 10:16 UTC, gds-gharper submitted a review, later dismissed

2020-08-26 12:00 UTC, gds-gharper approved these changes

2020-08-26 12:04 UTC, merged