notification role fix
alphagov/co-eu-transition-dashboard pull request #245
Opened 2020-09-01 17:05 UTC by AhdabNasir

2020-09-02 10:08 UTC, dtaylor7 requested changes

2020-09-02 10:08 UTC, dtaylor7 commented on notifications/upcomingMilestones.js
> +      model: Role,
i think we need to add `required: true` here. it may be worth checking this emails the correct people

2020-09-16 10:37 UTC, dtaylor7 submitted a review, later dismissed

2020-09-17 11:49 UTC, gds-gharper approved these changes

2020-09-17 12:10 UTC, merged