entity user permissions
alphagov/co-eu-transition-dashboard pull request #248
Opened 2020-09-03 13:48 UTC by dtaylor7

- add a new table to link users to entities
 - only allow export of entities to users with permissions to those entities
 - only allow the import of entities to users with permissions to those entities
 - allow admin to export/import all entites

2020-09-03 14:17 UTC, gds-gharper requested changes

2020-09-03 14:17 UTC, gds-gharper commented on migrations/16_entity_upload_permissions.js
> +      type: Sequelize.DataTypes.INTEGER,
We should use a consistent type for id's, below you're using `Sequelize.INTEGER(10).UNSIGNED` and here you're using `Sequelize.DataTypes.INTEGER`

2020-09-03 14:17 UTC, gds-gharper commented on migrations/16_entity_upload_permissions.js
> +  await query.bulkDelete('category', { name: 'Department' });
Is there a unique key on the name field in category?

2020-09-03 14:17 UTC, gds-gharper commented on pages/data-entry-entity/category-template/CategoryTemplate.js
> +    const userIsAdmin = this.req.user.roles.map(role => role.name).includes('admin');
This might be worth having as a function in the user model

isAdmin, isViewer etc.  I get the feeling it'll be used in quite a few places and it's worthwhile making it common.

2020-09-15 08:30 UTC, dtaylor7 commented on migrations/16_entity_upload_permissions.js
> +      type: Sequelize.DataTypes.INTEGER,
the only reason i am using Sequelize.INTEGER(10).UNSIGNED is so that it matches user table. `Sequelize.DataTypes.INTEGER` will not work for the entity table

2020-09-15 08:31 UTC, dtaylor7 commented on migrations/16_entity_upload_permissions.js
> +  await query.bulkDelete('category', { name: 'Department' });
yes, an id, but I cannot use this as I don't know what the id will be

2020-09-15 11:22 UTC, gds-gharper commented on migrations/16_entity_upload_permissions.js
> +  await query.bulkDelete('category', { name: 'Department' });
Ok, so long as the name field is unique then this is fine, though you may not need to use bulkDelete, it likely doesn't matter though.

2020-09-15 11:26 UTC, gds-gharper commented on migrations/16_entity_upload_permissions.js
> +      type: Sequelize.DataTypes.INTEGER,
In general unless there's a reason to have negative numbers/ids you should always try to use unsigned integers for ID fields.  It does look like I missed this off the mysql workbench stuff though, my bad, we should potentially change this across the field in a future update, may be worth creating a ticket for it

2020-09-15 11:49 UTC, gds-gharper requested changes

2020-09-15 11:49 UTC, gds-gharper commented on middleware/entityUserPermissions.js
> +  });
You may want to be careful about double joins in different directions here.  worth checking the SQL and making sure it doesn't multiply.  ```DEBUG=sequelize:sql* npm run dev``` will help there (and give you query timings as well.

2020-09-15 11:49 UTC, gds-gharper commented on middleware/entityUserPermissions.js
> +      seperate: true,
`seperate` should be `separate`

2020-09-15 11:58 UTC, dtaylor7 commented on middleware/entityUserPermissions.js
> +  });
have checked the speed and its 3ms locally

2020-09-15 12:00 UTC, dtaylor7 commented on middleware/entityUserPermissions.js
> +      seperate: true,
good catch, i have removed this in this case, apparently only works on hasMany relations

2020-09-15 12:06 UTC, gds-gharper commented on middleware/entityUserPermissions.js
> +  });
It's mostly the number of rows I'm concerned about (speed can help diagnose this) in this case it should be fine since you're limiting it to only one user.

2020-09-15 12:06 UTC, gds-gharper approved these changes

2020-09-15 13:49 UTC, merged