Dont map projects with NO milestones & hide decommissioned milestones
alphagov/co-eu-transition-dashboard pull request #329
Opened 2020-10-01 14:59 UTC by dtaylor7

- Dont map projects with NO milestones
- hide decommissioned milestones

2020-10-01 15:34 UTC, gds-gharper requested changes

2020-10-01 15:34 UTC, gds-gharper commented on helpers/transitionReadinessData.js
> +  // }
testing/debugging or actually removing it.  If so we should probably delete rather than comment out.

It also might be worth moving the cache into its own module, as such it's abstracted from redis if we want to change/remove it in future.

2020-10-02 09:27 UTC, dtaylor7 commented on helpers/transitionReadinessData.js
> +  // }
all done

2020-10-02 09:28 UTC, gds-gharper approved these changes

2020-10-02 09:29 UTC, merged