cron for clearing cache
alphagov/co-eu-transition-dashboard pull request #331
Opened 2020-10-02 14:06 UTC by dtaylor7

- create a feature for caching so we can turn this off easily 
- reset cache at midnight

2020-10-02 14:09 UTC, gds-gharper reviewed
You can set an expiry on redis keys, why not just use that rather than using a cron?

2020-10-02 14:12 UTC, dtaylor7 commented
> You can set an expiry on redis keys, why not just use that rather than using a cron?

is there a way to expire the cache at a specific time?

2020-10-02 14:32 UTC, gds-gharper commented
> > You can set an expiry on redis keys, why not just use that rather than using a cron?
> 
> is there a way to expire the cache at a specific time?

You can specify a number of seconds/milliseconds to expire it in.  You could always just calculate the number of seconds/milliseconds until <x> (so midnight tomorrow - now + some fudge factor) and then set it at that.  The advantage of that is it'll just happen automatically in the background with no overhead.

2020-10-02 14:44 UTC, dtaylor7 commented
> > > You can set an expiry on redis keys, why not just use that rather than using a cron?
> > 
> > 
> > is there a way to expire the cache at a specific time?
> 
> You can specify a number of seconds/milliseconds to expire it in. You could always just calculate the number of seconds/milliseconds until (so midnight tomorrow - now + some fudge factor) and then set it at that. The advantage of that is it'll just happen automatically in the background with no overhead.
> 
> Edit: just looking expireat does what you want https://redis.io/commands/expireat

Yes I saw that just now too. Can't see how to do this with npm redis. is using cron really a no go?

2020-10-02 15:03 UTC, gds-gharper commented
> > > > You can set an expiry on redis keys, why not just use that rather than using a cron?
> > > 
> > > 
> > > is there a way to expire the cache at a specific time?
> > 
> > 
> > You can specify a number of seconds/milliseconds to expire it in. You could always just calculate the number of seconds/milliseconds until (so midnight tomorrow - now + some fudge factor) and then set it at that. The advantage of that is it'll just happen automatically in the background with no overhead.
> > Edit: just looking expireat does what you want https://redis.io/commands/expireat
> 
> Yes I saw that just now too. Can't see how to do this with npm redis. is using cron really a no go?

The library states it's s 1-1 mapping of commands from redis and that you should use the redis command reference for the details.  expireat has been in since 1.2 so it should support it.  have you tried just calling expireat(timestamp) ?

2020-10-02 15:24 UTC, dtaylor7 commented
> > > > > You can set an expiry on redis keys, why not just use that rather than using a cron?
> > > > 
> > > > 
> > > > is there a way to expire the cache at a specific time?
> > > 
> > > 
> > > You can specify a number of seconds/milliseconds to expire it in. You could always just calculate the number of seconds/milliseconds until (so midnight tomorrow - now + some fudge factor) and then set it at that. The advantage of that is it'll just happen automatically in the background with no overhead.
> > > Edit: just looking expireat does what you want https://redis.io/commands/expireat
> > 
> > 
> > Yes I saw that just now too. Can't see how to do this with npm redis. is using cron really a no go?
> 
> The library states it's s 1-1 mapping of commands from redis and that you should use the redis command reference for the details. expireat has been in since 1.2 so it should support it. have you tried just calling expireat(timestamp) ?
> 
> Worst case scenario you could add the command yourself: https://www.npmjs.com/package/redis#clientsend_commandcommand_name-args-callback

ok, I have updated

2020-10-02 15:38 UTC, gds-gharper requested changes

2020-10-02 15:38 UTC, gds-gharper commented on helpers/transitionReadinessData.js
>    }
I would check that the feature is enabled before interacting with the cache/redis at all

2020-10-02 15:38 UTC, gds-gharper commented on helpers/transitionReadinessData.js
> +  await redis.set(`cache-transition-${topLevelEntityPublicId}`, JSON.stringify(topLevelEntityMapped), moment().endOf('day').format('x'));
Check for the cache feature enabled before setting?

Also redis expects the unix epoch in seconds, nor milliseconds (X rather than x).

You can use `endOf('day').unix()` rather than dropping to format which should be faster too.

Please test this locally to make sure things are expiring, you can check the expiry of a key in the redis client by calling TTL <key>

As an aside, I'm not sure calling this function set is wise, I had assumed the object here was a standard redis object and that you were calling set on it, when you've actually defined your own set function with very different calling parameters to the standard.

I'd be tempted not to call it a redis object (which compounds the confusion) simply call it a cache object. cache.set("key","expiry") would be fine, it's the fact that it's called redis which makes this confusing.

If that's the case I'd be tempted to just pass in a moment object to the expiry and convert it inside the redis library, that way it's pretty agnostic if/when we ever change the mechanism

2020-10-02 15:58 UTC, dtaylor7 commented on helpers/transitionReadinessData.js
> +  await redis.set(`cache-transition-${topLevelEntityPublicId}`, JSON.stringify(topLevelEntityMapped), moment().endOf('day').format('x'));
done

2020-10-02 16:04 UTC, gds-gharper requested changes

2020-10-02 16:04 UTC, gds-gharper commented on helpers/transitionReadinessData.js
> +  if(config.features.transitionReadinessCache && cached) {
You're still fetching from the cache here, just throwing it away afterwards.  I would consider putting the config check inside the cache service and just returning null/false on set/get if it's disabled, that way you don't have to worry about it in any code

2020-10-02 16:06 UTC, dtaylor7 commented on helpers/transitionReadinessData.js
> +  if(config.features.transitionReadinessCache && cached) {
ultimately this is only for development, but I will change again

2020-10-05 08:19 UTC, gds-gharper approved these changes

2020-10-05 14:18 UTC, merged