DDB-881 - simple measure data page
alphagov/co-eu-transition-dashboard pull request #334
Opened 2020-10-06 10:28 UTC by leighjohnson-friday

The initial page for editing measure data.  Pulls through measure data and displays a simple table.

2020-10-06 11:56 UTC, gds-gharper commented on common/views/navigation.njk
> +    <li class="govuk-header__navigation-item child-item {{ 'govuk-header__navigation-item--active' if url in addEntitiesUrls and not config.paths.dataEntryEntity.measureEdit }}">
Won't `url in addEntitiesUrls and not config.paths.dataEntryEntity.measureEdit` evaluate to (url in addEntitiesUrls) and (not config.paths.dataEntryEntity.measureEdit) which will always be false, since config.paths.dataEntryEntity.measureEdit will always be true (as it's set)?

2020-10-06 12:17 UTC, leighjohnson-friday commented on common/views/navigation.njk
> +    <li class="govuk-header__navigation-item child-item {{ 'govuk-header__navigation-item--active' if url in addEntitiesUrls and not config.paths.dataEntryEntity.measureEdit }}">
You are correct.  Added a new array for measure URL's to fix the issue.

2020-10-07 08:28 UTC, dtaylor7 requested changes
Looking really good, just a few comments that could possibly simplify the code a little

2020-10-07 08:28 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +  async getCategory() {
suggestion: this could be renamed to `getMeasureCategory` to better describe the function

2020-10-07 08:28 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +        model: Entity,
perhaps a couple of comments here to explain why the deep joins i.e.:

```
        // get direct parent of measure i.e. outcome statement
        model: Entity,
        as: 'parents',
        include: [{
          model: Category
        }, {
        // get direct parents of outcome statement i.e. theme ( and possibly another outcome statement )
          model: Entity,
          as: 'parents',
          include: Category
        }]
```

2020-10-07 08:28 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +        model: EntityFieldEntry,
you can add `separate: true` here to speed up the request

2020-10-07 08:28 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +      entity['entityFieldEntries'] = await this.getEntityFields(entity.id)
you should already have the entity field entries for each entity from the above query under `entity. entityFieldEntries`

2020-10-07 08:28 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +  async getMeasureTheme(parents) {
with the query here: https://github.com/alphagov/co-eu-transition-dashboard/pull/334/files#diff-64b080c92e904557ee5fd4d9d592f928R48. you should be able to get theme for each entity, see my PR https://github.com/alphagov/co-eu-transition-dashboard/pull/332/files#diff-2dd26fe17f01dc3c66213f75d0e37e78R52

2020-10-07 09:42 UTC, leighjohnson-friday commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +      entity['entityFieldEntries'] = await this.getEntityFields(entity.id)
Due to the where clause, we need to fetch these separately.  I tried a solution include 2 joins for the entityFieldEntries model but this had a similar issue and this seemed the best solution.

2020-10-07 09:43 UTC, leighjohnson-friday commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +        model: EntityFieldEntry,
Adding separate actually breaks the query and return other non-related entities so I've left this as it is. Think we need to  keep this as a join query.

2020-10-07 11:12 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +        model: EntityFieldEntry,
aha yes, it guess its because of the where clause

2020-10-07 11:13 UTC, dtaylor7 commented on pages/data-entry-entity/measure-edit/MeasureEdit.js
> +      entity['entityFieldEntries'] = await this.getEntityFields(entity.id)
yep fair enough

2020-10-07 11:14 UTC, dtaylor7 approved these changes

2020-10-07 11:54 UTC, merged