Da readiness overview page
alphagov/co-eu-transition-dashboard pull request #356
Opened 2020-10-20 12:39 UTC by AhdabNasir

2020-10-20 13:48 UTC, dtaylor7 requested changes

2020-10-20 13:48 UTC, dtaylor7 commented on pages/theme/Theme.html
> +      <p class="govuk-body">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown pr
should we hide this until we have real data in?

2020-10-20 13:48 UTC, dtaylor7 commented on pages/theme/Theme.html
> +      <p class="govuk-body">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown pr
or maybe wrap in a feature flag so it doesn't get pushed to prod by accident?

2020-10-20 13:51 UTC, AhdabNasir commented on pages/theme/Theme.html
> +      <p class="govuk-body">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown pr
Thank you for spotting this! I forgot to replace that with `<p class="govuk-body">{{ data.theme.comment }}</p>` just did that now

2020-10-20 13:53 UTC, AhdabNasir commented on pages/theme/Theme.html
> +      <p class="govuk-body">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown pr
Only if there's comments in the Comment field in the Theme Category then it will display. If there's no comment then nothing will display. So not sure if a feature flag is needed?

2020-10-21 12:28 UTC, closed without merging

2020-10-21 12:28 UTC, AhdabNasir commented
Closing this for now until we work on this again