DDB-499: create user
alphagov/co-eu-transition-dashboard pull request #373
Opened 2020-10-27 11:44 UTC by mateen-hussain

* Create User Form page
** Validates if user already exists
** validates for required fields (roles/departments)
** Sends email notification on successful creation
* Create User confirmation page
* "Create User" button on Manage-users-list page
* Unit tests

2020-10-27 11:56 UTC, dtaylor7 reviewed
great first PR, looks really good.

just checking when you are on create-user page that the top bar navigation highlights you are still in admin -> manage users section?

2020-10-27 11:57 UTC, dtaylor7 commented on pages/admin/user-management/create-user/CreateUser.js
> +  async createUser({ email, roles, departments }) {
could also look into breaking this function down a little bit to reduce complexity. but not essential

2020-10-27 11:58 UTC, dtaylor7 commented on pages/admin/user-management/create-user/CreateUser.js
> +    }))
side note: missing semi-colon here, could do with adding that to eslint at some point as its all over the code.

2020-10-27 12:02 UTC, mateen-hussain commented on pages/admin/user-management/create-user/CreateUser.js
> +  async createUser({ email, roles, departments }) {
I did think of breaking it further, but that would mean added complexity of implementing transaction rollback. So decided to stick with it.

2020-10-27 12:04 UTC, mateen-hussain commented on pages/admin/user-management/create-user/CreateUser.js
> +    }))
sorry, a bit lazy in adding semi-colons. Let me see if I can modify eslint rule to auto add them.

2020-10-27 12:05 UTC, mateen-hussain commented
> great first PR, looks really good.
> 
> just checking when you are on create-user page that the top bar navigation highlights you are still in admin -> manage users section?

I am not aware of this. Let me check and get back to you on this.

2020-10-27 12:09 UTC, mateen-hussain commented
> great first PR, looks really good.
> 
> just checking when you are on create-user page that the top bar navigation highlights you are still in admin -> manage users section?

Just checked, the top navigation bar highlighting admin -> manage is not present. Good spot. Will add it.

2020-10-27 14:12 UTC, dtaylor7 approved these changes

2020-10-27 17:20 UTC, dtaylor7 submitted a review, later dismissed

2020-10-28 09:11 UTC, gds-gharper requested changes

2020-10-28 09:11 UTC, gds-gharper commented on pages/admin/user-management/create-user/CreateUser.js
> +const VALIDATION_ERROR_MESSSAGE = 'VALIDATION_ERROR'
There's quite a mixture of lines terminating with semi-colons and lines without.  I'm aware modern ECMA doesn't require semi-colons anymore however we should try to be consistent.

2020-10-28 09:11 UTC, gds-gharper commented on pages/admin/user-management/create-user/CreateUser.js
> +    }));
I tend to use ternaries when I want to get everything onto one line (usually a simple return) as it's more readable.  Especially here when you've broken onto multiple lines anyway I would tend to actually write out an if statement, simply for ease of reading.

2020-10-28 09:11 UTC, gds-gharper commented on pages/admin/user-management/create-user/CreateUser.js
> +      logger.info(`User ${user.email} created`);
It might be worth logging the departments and the roles here too.

2020-10-28 09:11 UTC, gds-gharper commented on pages/admin/user-management/create-user/CreateUser.js
> +    if (notify.apiKey) {
In this case what happens if the apiKey isn't set.  The password is never output anywhere. I guess you got this from the createUser script.

I think for the user interface we should require the apiKey to be set and simply mock this out in the tests.

There's also a debate whether or not failing to email the user here constitutes a failure to create the user and should require a transaction rollback.  We should certainly let the admin know that we were unable to send the email (this happens on staging a lot as there's an email whitelist)

2020-10-28 09:11 UTC, gds-gharper commented on pages/admin/user-management/create-user/CreateUser.js
> +  async sendUserCreationEmailConfirmation(user, passphrase) {
Is there any need for this to be an async function?

It doesn't use await or any of that functionality.

2020-10-28 09:27 UTC, mateen-hussain commented on pages/admin/user-management/create-user/CreateUser.js
> +const VALIDATION_ERROR_MESSSAGE = 'VALIDATION_ERROR'
fixed

2020-10-28 09:31 UTC, mateen-hussain commented on pages/admin/user-management/create-user/CreateUser.js
> +    }));
agreed. Fixed

2020-10-28 09:42 UTC, mateen-hussain commented on pages/admin/user-management/create-user/CreateUser.js
> +  async sendUserCreationEmailConfirmation(user, passphrase) {
good spot, `notifyCLient.sendEmail` is an `async` function. Will add an await there.

2020-10-28 09:44 UTC, mateen-hussain commented on pages/admin/user-management/create-user/CreateUser.js
> +    if (notify.apiKey) {
I'll PM you to get better understanding of this :)

2020-10-28 15:35 UTC, gds-gharper approved these changes

2020-10-28 16:25 UTC, merged