show projects with no milestones within transition overview
alphagov/co-eu-transition-dashboard pull request #451
Opened 2020-11-26 16:25 UTC by dtaylor7

2020-11-26 16:41 UTC, gds-gharper commented
It would be useful to give us the ticket number for this

2020-11-26 16:49 UTC, gds-gharper requested changes

2020-11-26 16:49 UTC, gds-gharper commented on helpers/transitionReadinessData.js
>      }
I think we can lose the productsCategory check here tbh and just delete children if it's empty.

2020-11-26 16:49 UTC, gds-gharper commented on helpers/transitionReadinessData.js
> +        }
Rather than do this here, I'd suggest doing it around line 302.

You can then do  ```if (!['Yes', 'No'].includes(milestone.complete)) { return false; }```

That's where the other milestone checks are, it would be good to keep them in one place

2020-11-27 09:51 UTC, dtaylor7 commented on helpers/transitionReadinessData.js
>      }
i removed as we clear our children in `mapEntityChildren`

2020-11-27 09:52 UTC, dtaylor7 commented
> It would be useful to give us the ticket number for this

https://technologyprogramme.atlassian.net/browse/DDB-1286

2020-11-27 11:30 UTC, AhdabNasir approved these changes

2020-11-27 13:29 UTC, merged