Cypress ui setup
alphagov/co-eu-transition-dashboard pull request #467
Opened 2020-12-02 14:11 UTC by hitengpatel

Hi @leighjohnson-friday and @dtaylor7,

This is my 1st Pull request on Cypress UI script. All the new files are located under test folder (cypress folder and cypress.json).
Apart from this there are few dependency updates on package.json. I hope this is not going to impact any code.

Thanks,
Hiten

2020-12-02 15:01 UTC, dtaylor7 requested changes
Excited to see this working!

There are a lot of comments throughout the code, i would be tempted to clean this up and only add comments where essential

2020-12-02 15:01 UTC, dtaylor7 commented on test/cypress/support/commands.js
> +// ***********************************************
this file can be removed?

2020-12-09 15:24 UTC, hitengpatel commented on package.json
> +    "mysql": "^2.18.1",
Using Mysql2 now

2020-12-09 17:00 UTC, hitengpatel commented on test/cypress.json
> +        "host": "localhost",
Removed now and using current /config

2020-12-14 09:35 UTC, dtaylor7 approved these changes

2020-12-17 14:52 UTC, leighjohnson-friday approved these changes

2020-12-17 14:52 UTC, merged