Cypress UI hmg delivery
alphagov/co-eu-transition-dashboard pull request #524
Opened 2020-12-30 12:52 UTC by hitengpatel

2020-12-30 14:44 UTC, mateen-hussain requested changes

2020-12-30 14:44 UTC, mateen-hussain commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment .js
> +function testSetup() {
looks like you are creating user for each test. Maybe move this a global setup, and save the user in a config which all tests can access.
As part of global teardown delete the user.
https://stackoverflow.com/questions/48110258/how-can-i-execute-code-before-all-tests-suite-with-cypress

2020-12-30 14:44 UTC, mateen-hussain commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment .js
> +function addrole(rolename) {
The `addRole` function is being duplicated. Any common functions move into some helper file.

2020-12-31 10:09 UTC, hitengpatel commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment .js
> +function testSetup() {
Now updated the code address above

2020-12-31 10:09 UTC, hitengpatel commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment .js
> +function addrole(rolename) {
Now updated the code address above

2020-12-31 10:35 UTC, mateen-hussain requested changes

2020-12-31 10:35 UTC, mateen-hussain commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment.js
> +const department = 'All';
use Uppercasing for variable constants. This is recommended pattern

Ex `const DEPARTMENT = 'all';`

2020-12-31 10:35 UTC, mateen-hussain commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment.js
> +    cy.on('uncaught:exception', () => {
I'm don't think it is a good practice to catch exceptions in a test, you might be masking some errors.

The only time I'd have an exception in a test is when I'm asserting an exception.

2020-12-31 10:35 UTC, mateen-hussain commented on test/cypress/pages/Admin.js
> +const Table_ConfirmDeleteMEasure = ".govuk-table";
const variable naming is not consistent. Use all uppercase for constants or cameCase.

2020-12-31 10:43 UTC, hitengpatel commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment.js
> +    cy.on('uncaught:exception', () => {
removed unnecessary exception

2020-12-31 10:44 UTC, mateen-hussain approved these changes
Happy for you to make these changes in your next PR.

2020-12-31 10:44 UTC, mateen-hussain commented on test/cypress/pages/HMGDelivery.js
> +    var regexp = new RegExp("^" + TXT_Openall + "$");
use `let`or `const` instead of `var` for variables.

2020-12-31 10:45 UTC, hitengpatel commented on test/cypress/pages/HMGDelivery.js
> +    var regexp = new RegExp("^" + TXT_Openall + "$");
will fix this in next PR for whole suite

2020-12-31 10:45 UTC, hitengpatel commented on test/cypress/pages/Admin.js
> +const Table_ConfirmDeleteMEasure = ".govuk-table";
will fix this in next PR for whole suite

2020-12-31 10:47 UTC, merged