Cypress UI missed milestone list
alphagov/co-eu-transition-dashboard pull request #536
Opened 2021-01-08 19:32 UTC by hitengpatel

2021-01-12 11:15 UTC, mateen-hussain commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment.js
> +const department = Cypress.config().department;
In ES6 JS there is a shorthand for this `const {department} = Cypress.config()`. You dont have to change this. Just information comment.

2021-01-12 11:19 UTC, mateen-hussain commented on test/cypress/support/index.js
>  const dev = require('../../../config/development.json')
optional you dont need `../` to import config.json. The project is configured to do look from root folder. Just use

`const { serviceUrl } = require('config');`

2021-01-12 11:22 UTC, mateen-hussain commented on test/cypress/support/utils.js
> +const groupBy = (list, callback) => {
see if you can use https://lodash.com/docs/4.17.15#groupBy. We already use lodash in our project and groupBy in helpers/measures.js

2021-01-12 11:22 UTC, mateen-hussain requested changes
check comments for details on requested changes.

2021-01-12 12:53 UTC, hitengpatel commented on test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment.js
> +const department = Cypress.config().department;
Ohh. That's good to know.

2021-01-12 12:55 UTC, hitengpatel commented on test/cypress/support/index.js
>  const dev = require('../../../config/development.json')
I did tried it earlier on but it does not work for some reason on cypress so i used ../ instead

2021-01-12 14:12 UTC, hitengpatel commented on test/cypress/support/utils.js
> +const groupBy = (list, callback) => {
I tested with above and it works. It helped me to use other functions from same lib. I will make changes.

2021-01-13 09:48 UTC, mateen-hussain commented on test/cypress/support/index.js
>  const dev = require('../../../config/development.json')
Check with @leighjohnson-friday It would be as simple as adding the folder to some config. Again this is optional.

2021-01-13 09:49 UTC, mateen-hussain commented on test/cypress/support/index.js
> +//import './utils'
Delete this comment

2021-01-13 09:50 UTC, mateen-hussain approved these changes

2021-01-13 13:13 UTC, merged